# Generated by Django 4.1.2 on 2022-11-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aparicion',
            unique_together={('fecha', 'empresa')},
        ),
    ]
