# Generated by Django 4.1.2 on 2022-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_aparicion_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparicion',
            name='fecha',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='datosplantacion',
            name='fecha',
            field=models.DateField(default='2022-11-11'),
        ),
    ]
