# Generated by Django 4.1.2 on 2022-10-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('representante', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=30)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.estacion')),
            ],
        ),
    ]
