# Generated by Django 4.1.2 on 2022-11-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.estacion'),
        ),
    ]
