# Generated by Django 4.1.2 on 2025-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='variedad_actual',
            field=models.CharField(choices=[('erecto', 'erecto'), ('rastrero', 'rastrero'), ('arrosetada', 'arrosetada')], max_length=20, null=True),
        ),
    ]
