# Generated by Django 4.1.2 on 2022-11-16 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipodealerta', models.CharField(choices=[('No aspersión', 'No aspersión'), ('Alerta Tizón', 'Alerta Tizón'), ('Aspersión cada 7 días', 'Aspersión cada 7 días'), ('Aspersión cada 5 días', 'Aspersión cada 5 días')], max_length=30)),
                ('tipodemensaje', models.CharField(choices=[('A', 'Alerta'), ('M', 'Mensaje'), ('C', 'Consulta')], max_length=11)),
                ('recibido', models.BooleanField(default=False, verbose_name='Recibido')),
                ('img', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
