# Generated by Django 4.1.2 on 2022-11-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='img',
            field=models.FileField(null=True, upload_to='static/vendor/'),
        ),
    ]
