# Generated by Django 4.1.2 on 2022-11-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensajes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='static/vendor/'),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='tipodealerta',
            field=models.CharField(blank=True, choices=[('No aspersión', 'No aspersión'), ('Alerta Tizón', 'Alerta Tizón'), ('Aspersión cada 7 días', 'Aspersión cada 7 días'), ('Aspersión cada 5 días', 'Aspersión cada 5 días')], max_length=30, null=True),
        ),
    ]
