# Generated by Django 4.1.2 on 2022-11-19 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_alter_mensajes_img_alter_mensajes_tipodealerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 22, 31, 16, 693951)),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 22, 31, 16, 693951)),
        ),
    ]
