# Generated by Django 4.1.2 on 2025-08-16 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0005_alter_mensajes_created_at_alter_mensajes_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 9, 33, 29, 777793)),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 9, 33, 29, 777793)),
        ),
    ]
