# Generated by Django 4.1.2 on 2022-10-30 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2022-10-29')),
                ('temperatura_media', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('temperatura_maxima', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('temperatura_minima', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('precipitacion', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('horas_hr_90', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('temperatura_media_hr_90', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('favorable', models.IntegerField(null=True)),
                ('severidad', models.IntegerField(null=True)),
                ('deteccion_inicial', models.IntegerField(null=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.estacion')),
            ],
            options={
                'unique_together': {('fecha', 'estacion')},
            },
        ),
    ]
