# Generated by Django 4.1.2 on 2022-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('clima', '0002_alter_clima_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clima',
            name='empresa',
            field=models.ManyToManyField(to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='fecha',
            field=models.DateField(default='2022-10-30'),
        ),
    ]
