# Generated by Django 4.1.2 on 2022-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0006_alter_clima_fecha_alter_clima_temperatura_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clima',
            name='horas_hr_90',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clima',
            name='precipitacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clima',
            name='temperatura_maxima',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clima',
            name='temperatura_media_hr_90',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clima',
            name='temperatura_minima',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
