# Generated by Django 4.1.2 on 2022-11-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_alter_clima_horas_hr_90_alter_clima_precipitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clima',
            name='fecha',
            field=models.DateField(default='2022-11-15'),
        ),
    ]
