# Generated by Django 4.1.2 on 2025-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0010_alter_clima_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clima',
            name='fecha',
            field=models.DateField(default='2025-08-16'),
        ),
    ]
